/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_bme300_server/gatt_bme300_server_db.dbi_
 */
#ifndef __GATT_BME300_SERVER_DB_H
#define __GATT_BME300_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_BME300_SERVICE           (0x0001)
#define HANDLE_BME300_SERVICE_END       (0xffff)
#define HANDLE_BME300_UART_RX           (0x0003)
#define HANDLE_BME300_RX_CLIENT_CONFIG  (0x0004)
#define HANDLE_BME300_UART_TX           (0x0006)
#define HANDLE_BME300_TX_CLIENT_CONFIG  (0x0007)

typedef enum
{
    BME300_SERVICE,
    
    gatt_sdp_last
} gatt_sdp;

uint8 *GattGetServiceRecord(gatt_sdp service, uint16 *len);
uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
