/*!
    \copyright Copyright (c) 2020 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version 
    \file chain_aac_stereo_decoder_right.h
    \brief The chain_aac_stereo_decoder_right chain. This file is generated by C:/qtil/ADK_QCC512X_QCC302X_WIN_6.4.2.26/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_AAC_STEREO_DECODER_RIGHT_H__
#define _CHAIN_AAC_STEREO_DECODER_RIGHT_H__

/*!
    @startuml
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
        object OPR_AAC_DECODER
        OPR_AAC_DECODER : id = EB_CAP_ID_AAC_DECODER
        object OPR_CONSUMER
        OPR_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
        OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
        OPR_CONSUMER "IN(0)"<-- "OUT_L(0)" OPR_AAC_DECODER
        object EPR_SINK_MEDIA #lightgreen
        OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MEDIA
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT_R(1)" OPR_AAC_DECODER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_aac_stereo_decoder_right_config;

#endif /* _CHAIN_AAC_STEREO_DECODER_RIGHT_H__ */

