/*!
    \copyright Copyright (c) 2020 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version 
    \file chain_forwarding_input_aac_stereo_right.h
    \brief The chain_forwarding_input_aac_stereo_right chain. This file is generated by C:/qtil/ADK_QCC512X_QCC302X_WIN_6.4.2.26/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_FORWARDING_INPUT_AAC_STEREO_RIGHT_H__
#define _CHAIN_FORWARDING_INPUT_AAC_STEREO_RIGHT_H__

/*!
    @startuml
        object OPR_RTP_DECODER
        OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
        object OPR_SPLITTER
        OPR_SPLITTER : id = CAP_ID_SPLITTER
        object OPR_AAC_DECODER
        OPR_AAC_DECODER : id = EB_CAP_ID_AAC_DECODER
        object OPR_CONSUMER
        OPR_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
        OPR_SPLITTER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
        OPR_AAC_DECODER "IN(0)"<-- "OUT_0(0)" OPR_SPLITTER
        OPR_CONSUMER "IN(0)"<-- "OUT_L(0)" OPR_AAC_DECODER
        object EPR_SINK_MEDIA #lightgreen
        OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
        object EPR_SOURCE_FORWARDING_MEDIA #lightblue
        EPR_SOURCE_FORWARDING_MEDIA <-- "OUT_1(1)" OPR_SPLITTER
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT_R(1)" OPR_AAC_DECODER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_forwarding_input_aac_stereo_right_config;

#endif /* _CHAIN_FORWARDING_INPUT_AAC_STEREO_RIGHT_H__ */

