/*!
    \copyright Copyright (c) 2020 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version 
    \file chain_aptx_mono_no_autosync_decoder.h
    \brief The chain_aptx_mono_no_autosync_decoder chain. This file is generated by C:/qtil/ADK_QCC512X_QCC302X_WIN_6.4.2.26/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_APTX_MONO_NO_AUTOSYNC_DECODER_H__
#define _CHAIN_APTX_MONO_NO_AUTOSYNC_DECODER_H__

/*!
    @startuml
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
        object OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
        OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC : id = CAP_ID_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
        OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
        object EPR_SINK_MEDIA #lightgreen
        OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MEDIA
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_aptx_mono_no_autosync_decoder_config;

#endif /* _CHAIN_APTX_MONO_NO_AUTOSYNC_DECODER_H__ */

