/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Wed Jul 10 21:49:08 2019. */

#ifndef PB_BEFLEX_BIOMECHENGINE_BME_PROTOCOL_PB_H_INCLUDED
#define PB_BEFLEX_BIOMECHENGINE_BME_PROTOCOL_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Beflex_BiomechEngine_Parameter_Type {
    Beflex_BiomechEngine_Parameter_Type_START = 0,
    Beflex_BiomechEngine_Parameter_Type_FINISH = 1
} Beflex_BiomechEngine_Parameter_Type;
#define _Beflex_BiomechEngine_Parameter_Type_MIN Beflex_BiomechEngine_Parameter_Type_START
#define _Beflex_BiomechEngine_Parameter_Type_MAX Beflex_BiomechEngine_Parameter_Type_FINISH
#define _Beflex_BiomechEngine_Parameter_Type_ARRAYSIZE ((Beflex_BiomechEngine_Parameter_Type)(Beflex_BiomechEngine_Parameter_Type_FINISH+1))

typedef enum _Beflex_BiomechEngine_Calibration_Type {
    Beflex_BiomechEngine_Calibration_Type_LOOK_FORWARD = 0,
    Beflex_BiomechEngine_Calibration_Type_LOOK_DOWN = 1,
    Beflex_BiomechEngine_Calibration_Type_FINISH = 2
} Beflex_BiomechEngine_Calibration_Type;
#define _Beflex_BiomechEngine_Calibration_Type_MIN Beflex_BiomechEngine_Calibration_Type_LOOK_FORWARD
#define _Beflex_BiomechEngine_Calibration_Type_MAX Beflex_BiomechEngine_Calibration_Type_FINISH
#define _Beflex_BiomechEngine_Calibration_Type_ARRAYSIZE ((Beflex_BiomechEngine_Calibration_Type)(Beflex_BiomechEngine_Calibration_Type_FINISH+1))

typedef enum _Beflex_BiomechEngine_Custom_Type {
    Beflex_BiomechEngine_Custom_Type_READ = 0,
    Beflex_BiomechEngine_Custom_Type_WRITE = 1
} Beflex_BiomechEngine_Custom_Type;
#define _Beflex_BiomechEngine_Custom_Type_MIN Beflex_BiomechEngine_Custom_Type_READ
#define _Beflex_BiomechEngine_Custom_Type_MAX Beflex_BiomechEngine_Custom_Type_WRITE
#define _Beflex_BiomechEngine_Custom_Type_ARRAYSIZE ((Beflex_BiomechEngine_Custom_Type)(Beflex_BiomechEngine_Custom_Type_WRITE+1))

/* Struct definitions */
typedef struct _Beflex_BiomechEngine_Calibration {
    char dummy_field;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Calibration) */
} Beflex_BiomechEngine_Calibration;

typedef struct _Beflex_BiomechEngine_Custom {
    char dummy_field;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Custom) */
} Beflex_BiomechEngine_Custom;

typedef struct _Beflex_BiomechEngine_FOTA {
    char dummy_field;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA) */
} Beflex_BiomechEngine_FOTA;

typedef struct _Beflex_BiomechEngine_Parameter {
    char dummy_field;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Parameter) */
} Beflex_BiomechEngine_Parameter;

typedef struct _Beflex_BiomechEngine_Calibration_Request {
    Beflex_BiomechEngine_Calibration_Type type;
    uint32_t period;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Calibration_Request) */
} Beflex_BiomechEngine_Calibration_Request;

typedef PB_BYTES_ARRAY_T(36) Beflex_BiomechEngine_Calibration_Response_calValue_t;
typedef struct _Beflex_BiomechEngine_Calibration_Response {
    Beflex_BiomechEngine_Calibration_Type type;
    bool success;
    Beflex_BiomechEngine_Calibration_Response_calValue_t calValue;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Calibration_Response) */
} Beflex_BiomechEngine_Calibration_Response;

typedef PB_BYTES_ARRAY_T(64) Beflex_BiomechEngine_Custom_Notification_data_t;
typedef struct _Beflex_BiomechEngine_Custom_Notification {
    uint32_t param;
    Beflex_BiomechEngine_Custom_Notification_data_t data;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Custom_Notification) */
} Beflex_BiomechEngine_Custom_Notification;

typedef PB_BYTES_ARRAY_T(64) Beflex_BiomechEngine_Custom_Request_data_t;
typedef struct _Beflex_BiomechEngine_Custom_Request {
    Beflex_BiomechEngine_Custom_Type type;
    uint32_t param;
    Beflex_BiomechEngine_Custom_Request_data_t data;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Custom_Request) */
} Beflex_BiomechEngine_Custom_Request;

typedef PB_BYTES_ARRAY_T(64) Beflex_BiomechEngine_Custom_Response_data_t;
typedef struct _Beflex_BiomechEngine_Custom_Response {
    Beflex_BiomechEngine_Custom_Type type;
    uint32_t param;
    bool success;
    Beflex_BiomechEngine_Custom_Response_data_t data;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Custom_Response) */
} Beflex_BiomechEngine_Custom_Response;

typedef struct _Beflex_BiomechEngine_FOTA_DfuRequest {
    uint32_t target;
    uint32_t chunkSize;
    uint32_t totalLength;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA_DfuRequest) */
} Beflex_BiomechEngine_FOTA_DfuRequest;

typedef struct _Beflex_BiomechEngine_FOTA_DfuResponse {
    bool success;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA_DfuResponse) */
} Beflex_BiomechEngine_FOTA_DfuResponse;

typedef struct _Beflex_BiomechEngine_FOTA_DfuResult {
    bool success;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA_DfuResult) */
} Beflex_BiomechEngine_FOTA_DfuResult;

typedef PB_BYTES_ARRAY_T(128) Beflex_BiomechEngine_FOTA_PacketRequest_value_t;
typedef struct _Beflex_BiomechEngine_FOTA_PacketRequest {
    Beflex_BiomechEngine_FOTA_PacketRequest_value_t value;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA_PacketRequest) */
} Beflex_BiomechEngine_FOTA_PacketRequest;

typedef struct _Beflex_BiomechEngine_FOTA_PacketResponse {
    bool success;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_FOTA_PacketResponse) */
} Beflex_BiomechEngine_FOTA_PacketResponse;

typedef struct _Beflex_BiomechEngine_Parameter_Gait {
    uint32_t state;
    uint32_t elapsed;
    uint32_t stepCount;
    float cadence;
    float stepWidth;
    float headAngle;
    float wssl_rgtl;
    float wssr_rgtr;
    float wdsl_rftl;
    float wdsr_rgtr;
    float wfpl_rmll;
    float wfpr_rmlr;
    float shock;
    float symmetry;
    float vo;
    float legStiffness;
    float consistency;
    float speed;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Parameter_Gait) */
} Beflex_BiomechEngine_Parameter_Gait;

typedef PB_BYTES_ARRAY_T(36) Beflex_BiomechEngine_Parameter_Request_calValue_t;
typedef struct _Beflex_BiomechEngine_Parameter_Request {
    Beflex_BiomechEngine_Parameter_Type type;
    uint32_t period;
    float height;
    Beflex_BiomechEngine_Parameter_Request_calValue_t calValue;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Parameter_Request) */
} Beflex_BiomechEngine_Parameter_Request;

typedef struct _Beflex_BiomechEngine_Parameter_Response {
    Beflex_BiomechEngine_Parameter_Type type;
    bool success;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Parameter_Response) */
} Beflex_BiomechEngine_Parameter_Response;

typedef struct _Beflex_BiomechEngine_Message {
    pb_size_t which_typeName;
    union {
        Beflex_BiomechEngine_Parameter_Request parameterRequest;
        Beflex_BiomechEngine_Parameter_Response parameterResponse;
        Beflex_BiomechEngine_Parameter_Gait parameterGait;
        Beflex_BiomechEngine_Calibration_Request calibrationRequest;
        Beflex_BiomechEngine_Calibration_Response calibrationResponse;
        Beflex_BiomechEngine_Custom_Request customRequest;
        Beflex_BiomechEngine_Custom_Response customResponse;
        Beflex_BiomechEngine_Custom_Notification customNotification;
        Beflex_BiomechEngine_FOTA_DfuRequest dfuRequest;
        Beflex_BiomechEngine_FOTA_DfuResponse dfuResponse;
        Beflex_BiomechEngine_FOTA_PacketRequest packetRequest;
        Beflex_BiomechEngine_FOTA_PacketResponse packetResponse;
        Beflex_BiomechEngine_FOTA_DfuResult dfuResult;
    } typeName;
/* @@protoc_insertion_point(struct:Beflex_BiomechEngine_Message) */
} Beflex_BiomechEngine_Message;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Beflex_BiomechEngine_Message_init_default {0, {Beflex_BiomechEngine_Parameter_Request_init_default}}
#define Beflex_BiomechEngine_Parameter_init_default {0}
#define Beflex_BiomechEngine_Parameter_Request_init_default {_Beflex_BiomechEngine_Parameter_Type_MIN, 0, 0, {0, {0}}}
#define Beflex_BiomechEngine_Parameter_Response_init_default {_Beflex_BiomechEngine_Parameter_Type_MIN, 0}
#define Beflex_BiomechEngine_Parameter_Gait_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Beflex_BiomechEngine_Calibration_init_default {0}
#define Beflex_BiomechEngine_Calibration_Request_init_default {_Beflex_BiomechEngine_Calibration_Type_MIN, 0}
#define Beflex_BiomechEngine_Calibration_Response_init_default {_Beflex_BiomechEngine_Calibration_Type_MIN, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_init_default {0}
#define Beflex_BiomechEngine_Custom_Request_init_default {_Beflex_BiomechEngine_Custom_Type_MIN, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_Response_init_default {_Beflex_BiomechEngine_Custom_Type_MIN, 0, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_Notification_init_default {0, {0, {0}}}
#define Beflex_BiomechEngine_FOTA_init_default   {0}
#define Beflex_BiomechEngine_FOTA_DfuRequest_init_default {0, 0, 0}
#define Beflex_BiomechEngine_FOTA_DfuResponse_init_default {0}
#define Beflex_BiomechEngine_FOTA_PacketRequest_init_default {{0, {0}}}
#define Beflex_BiomechEngine_FOTA_PacketResponse_init_default {0}
#define Beflex_BiomechEngine_FOTA_DfuResult_init_default {0}
#define Beflex_BiomechEngine_Message_init_zero   {0, {Beflex_BiomechEngine_Parameter_Request_init_zero}}
#define Beflex_BiomechEngine_Parameter_init_zero {0}
#define Beflex_BiomechEngine_Parameter_Request_init_zero {_Beflex_BiomechEngine_Parameter_Type_MIN, 0, 0, {0, {0}}}
#define Beflex_BiomechEngine_Parameter_Response_init_zero {_Beflex_BiomechEngine_Parameter_Type_MIN, 0}
#define Beflex_BiomechEngine_Parameter_Gait_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Beflex_BiomechEngine_Calibration_init_zero {0}
#define Beflex_BiomechEngine_Calibration_Request_init_zero {_Beflex_BiomechEngine_Calibration_Type_MIN, 0}
#define Beflex_BiomechEngine_Calibration_Response_init_zero {_Beflex_BiomechEngine_Calibration_Type_MIN, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_init_zero    {0}
#define Beflex_BiomechEngine_Custom_Request_init_zero {_Beflex_BiomechEngine_Custom_Type_MIN, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_Response_init_zero {_Beflex_BiomechEngine_Custom_Type_MIN, 0, 0, {0, {0}}}
#define Beflex_BiomechEngine_Custom_Notification_init_zero {0, {0, {0}}}
#define Beflex_BiomechEngine_FOTA_init_zero      {0}
#define Beflex_BiomechEngine_FOTA_DfuRequest_init_zero {0, 0, 0}
#define Beflex_BiomechEngine_FOTA_DfuResponse_init_zero {0}
#define Beflex_BiomechEngine_FOTA_PacketRequest_init_zero {{0, {0}}}
#define Beflex_BiomechEngine_FOTA_PacketResponse_init_zero {0}
#define Beflex_BiomechEngine_FOTA_DfuResult_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define Beflex_BiomechEngine_Calibration_Request_type_tag 1
#define Beflex_BiomechEngine_Calibration_Request_period_tag 2
#define Beflex_BiomechEngine_Calibration_Response_type_tag 1
#define Beflex_BiomechEngine_Calibration_Response_success_tag 2
#define Beflex_BiomechEngine_Calibration_Response_calValue_tag 3
#define Beflex_BiomechEngine_Custom_Notification_param_tag 1
#define Beflex_BiomechEngine_Custom_Notification_data_tag 2
#define Beflex_BiomechEngine_Custom_Request_type_tag 1
#define Beflex_BiomechEngine_Custom_Request_param_tag 2
#define Beflex_BiomechEngine_Custom_Request_data_tag 3
#define Beflex_BiomechEngine_Custom_Response_type_tag 1
#define Beflex_BiomechEngine_Custom_Response_param_tag 2
#define Beflex_BiomechEngine_Custom_Response_success_tag 3
#define Beflex_BiomechEngine_Custom_Response_data_tag 4
#define Beflex_BiomechEngine_FOTA_DfuRequest_target_tag 1
#define Beflex_BiomechEngine_FOTA_DfuRequest_chunkSize_tag 2
#define Beflex_BiomechEngine_FOTA_DfuRequest_totalLength_tag 3
#define Beflex_BiomechEngine_FOTA_DfuResponse_success_tag 1
#define Beflex_BiomechEngine_FOTA_DfuResult_success_tag 1
#define Beflex_BiomechEngine_FOTA_PacketRequest_value_tag 1
#define Beflex_BiomechEngine_FOTA_PacketResponse_success_tag 1
#define Beflex_BiomechEngine_Parameter_Gait_state_tag 1
#define Beflex_BiomechEngine_Parameter_Gait_elapsed_tag 2
#define Beflex_BiomechEngine_Parameter_Gait_stepCount_tag 3
#define Beflex_BiomechEngine_Parameter_Gait_cadence_tag 4
#define Beflex_BiomechEngine_Parameter_Gait_stepWidth_tag 5
#define Beflex_BiomechEngine_Parameter_Gait_headAngle_tag 6
#define Beflex_BiomechEngine_Parameter_Gait_wssl_rgtl_tag 7
#define Beflex_BiomechEngine_Parameter_Gait_wssr_rgtr_tag 8
#define Beflex_BiomechEngine_Parameter_Gait_wdsl_rftl_tag 9
#define Beflex_BiomechEngine_Parameter_Gait_wdsr_rgtr_tag 10
#define Beflex_BiomechEngine_Parameter_Gait_wfpl_rmll_tag 11
#define Beflex_BiomechEngine_Parameter_Gait_wfpr_rmlr_tag 12
#define Beflex_BiomechEngine_Parameter_Gait_shock_tag 13
#define Beflex_BiomechEngine_Parameter_Gait_symmetry_tag 14
#define Beflex_BiomechEngine_Parameter_Gait_vo_tag 15
#define Beflex_BiomechEngine_Parameter_Gait_legStiffness_tag 16
#define Beflex_BiomechEngine_Parameter_Gait_consistency_tag 17
#define Beflex_BiomechEngine_Parameter_Gait_speed_tag 18
#define Beflex_BiomechEngine_Parameter_Request_type_tag 1
#define Beflex_BiomechEngine_Parameter_Request_period_tag 2
#define Beflex_BiomechEngine_Parameter_Request_height_tag 3
#define Beflex_BiomechEngine_Parameter_Request_calValue_tag 4
#define Beflex_BiomechEngine_Parameter_Response_type_tag 1
#define Beflex_BiomechEngine_Parameter_Response_success_tag 2
#define Beflex_BiomechEngine_Message_parameterRequest_tag 1
#define Beflex_BiomechEngine_Message_parameterResponse_tag 2
#define Beflex_BiomechEngine_Message_parameterGait_tag 3
#define Beflex_BiomechEngine_Message_calibrationRequest_tag 4
#define Beflex_BiomechEngine_Message_calibrationResponse_tag 5
#define Beflex_BiomechEngine_Message_customRequest_tag 6
#define Beflex_BiomechEngine_Message_customResponse_tag 7
#define Beflex_BiomechEngine_Message_customNotification_tag 8
#define Beflex_BiomechEngine_Message_dfuRequest_tag 9
#define Beflex_BiomechEngine_Message_dfuResponse_tag 10
#define Beflex_BiomechEngine_Message_packetRequest_tag 11
#define Beflex_BiomechEngine_Message_packetResponse_tag 12
#define Beflex_BiomechEngine_Message_dfuResult_tag 13

/* Struct field encoding specification for nanopb */
extern const pb_field_t Beflex_BiomechEngine_Message_fields[14];
extern const pb_field_t Beflex_BiomechEngine_Parameter_fields[1];
extern const pb_field_t Beflex_BiomechEngine_Parameter_Request_fields[5];
extern const pb_field_t Beflex_BiomechEngine_Parameter_Response_fields[3];
extern const pb_field_t Beflex_BiomechEngine_Parameter_Gait_fields[19];
extern const pb_field_t Beflex_BiomechEngine_Calibration_fields[1];
extern const pb_field_t Beflex_BiomechEngine_Calibration_Request_fields[3];
extern const pb_field_t Beflex_BiomechEngine_Calibration_Response_fields[4];
extern const pb_field_t Beflex_BiomechEngine_Custom_fields[1];
extern const pb_field_t Beflex_BiomechEngine_Custom_Request_fields[4];
extern const pb_field_t Beflex_BiomechEngine_Custom_Response_fields[5];
extern const pb_field_t Beflex_BiomechEngine_Custom_Notification_fields[3];
extern const pb_field_t Beflex_BiomechEngine_FOTA_fields[1];
extern const pb_field_t Beflex_BiomechEngine_FOTA_DfuRequest_fields[4];
extern const pb_field_t Beflex_BiomechEngine_FOTA_DfuResponse_fields[2];
extern const pb_field_t Beflex_BiomechEngine_FOTA_PacketRequest_fields[2];
extern const pb_field_t Beflex_BiomechEngine_FOTA_PacketResponse_fields[2];
extern const pb_field_t Beflex_BiomechEngine_FOTA_DfuResult_fields[2];

/* Maximum encoded size of messages (where known) */
#define Beflex_BiomechEngine_Message_size        134
#define Beflex_BiomechEngine_Parameter_size      0
#define Beflex_BiomechEngine_Parameter_Request_size 51
#define Beflex_BiomechEngine_Parameter_Response_size 4
#define Beflex_BiomechEngine_Parameter_Gait_size 96
#define Beflex_BiomechEngine_Calibration_size    0
#define Beflex_BiomechEngine_Calibration_Request_size 8
#define Beflex_BiomechEngine_Calibration_Response_size 42
#define Beflex_BiomechEngine_Custom_size         0
#define Beflex_BiomechEngine_Custom_Request_size 74
#define Beflex_BiomechEngine_Custom_Response_size 76
#define Beflex_BiomechEngine_Custom_Notification_size 72
#define Beflex_BiomechEngine_FOTA_size           0
#define Beflex_BiomechEngine_FOTA_DfuRequest_size 18
#define Beflex_BiomechEngine_FOTA_DfuResponse_size 2
#define Beflex_BiomechEngine_FOTA_PacketRequest_size 131
#define Beflex_BiomechEngine_FOTA_PacketResponse_size 2
#define Beflex_BiomechEngine_FOTA_DfuResult_size 2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BME_PROTOCOL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
