/*!
    \copyright Copyright (c) 2020 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version 
    \file chain_leakthrough_aec.h
    \brief The chain_leakthrough_aec chain. This file is generated by C:/qtil/ADK_QCC512X_QCC302X_WIN_6.4.2.26/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_LEAKTHROUGH_AEC_H__
#define _CHAIN_LEAKTHROUGH_AEC_H__

/*!
    @startuml
        object OPR_LEAKTHROUGH_AEC
        OPR_LEAKTHROUGH_AEC : id = CAP_ID_DOWNLOAD_AEC_REFERENCE
        object OPR_LEAKTHROUGH_INPUT_SPC
        OPR_LEAKTHROUGH_INPUT_SPC : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
        OPR_LEAKTHROUGH_INPUT_SPC "IN(0)"<-- "MIC1_OUT(3)" OPR_LEAKTHROUGH_AEC
        object EPR_LEAKTHROUGH_IN #lightgreen
        OPR_LEAKTHROUGH_AEC "SPEAKER1_IN(0)" <-- EPR_LEAKTHROUGH_IN
        object EPR_A2DP_LEAKTHROUGH_AEC_OUT #lightblue
        EPR_A2DP_LEAKTHROUGH_AEC_OUT <-- "SPEAKER1_OUT(1)" OPR_LEAKTHROUGH_AEC
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_leakthrough_aec_config;

#endif /* _CHAIN_LEAKTHROUGH_AEC_H__ */

